[mypy]
plugins = numpy.typing.mypy_plugin
ignore_missing_imports = True
explicit_package_bases = True

[mypy-matplotlib.*]
ignore_missing_imports = True

[mypy-experiments.01_drift_discovery.*]
ignore_errors = True

[mypy-yaml.*]
ignore_missing_imports = True


[mypy-src.kalmanorix.benchmarks.*]
ignore_errors = True

[mypy-src.kalmanorix.kalman_engine.*]
ignore_errors = True

[mypy-src.kalmanorix.datasets]
ignore_errors = True

[mypy-src.kalmanorix.panoramix]
ignore_errors = True

[mypy-src.kalmanorix.uncertainty_calibration]
ignore_errors = True

[mypy-experiments.*]
ignore_errors = True

[mypy-tests.*]
ignore_errors = True
